### ISSUE TITLE
redirects 

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/design.ubuntu.com#103]
can we setup a few redirects

- /apps* -> https://docs.ubuntu.com/phone/en/apps/index
- /scopes* -> https://docs.ubuntu.com/phone/en/scopes/index
- /web/{other stuff} -> /web
- /examples* -> /
- /audiences* -> /

**Comment by pmahnke** [comment]
@WillMoggridge or @tbille I assume this should be an RT and done on the webserver level?

If so, could you make that RT with the correct format?

**Comment by nottrobin** [comment]
Submitted PR for `/apps` and `/scopes`.

As discussed, we can't and shouldn't do `/web/{non-existent-pages}`, we should redirect specific old URLs, if we know them. And we should leave deleted sections `examples` and `audiences` to 404.

@pmahnke please open a new issue for `/web` pages if you find specific URLs.
