### ISSUE TITLE
Redesign design.ubuntu.com

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/design.ubuntu.com#138]

**Comment by anasereijo** [comment]
dup

**Comment by sladen** [comment]
In what way should design.u.c be redesign?  And which is the duplicate bug number?

**Comment by anthonydillon** [comment]
@sladen we are kicking off a project to redesign the entire design.ubuntu.com site and experience. This card was created as the milestone but should have be created in our teams repo.
