### ISSUE TITLE
Add social icons to footer

### ISSUE THREAD

**Issue by yaili** [canonical-websites/design.ubuntu.com#17]
Add:
- Design blog
- Twitter account
- Instagram account

Use same pattern as in the footer of https://jujucharms.com/

**Comment by pmahnke** [comment]
@spencerbygraves could you help?

the existing svg maps that I can find are here: https://manager.assets.ubuntu.com/?q=icon-social.svg

however, there are none for instagram

I assume we should just keep building up a single set?  so [this](https://assets.ubuntu.com/v1/77e84f57-icon-social.svg) appears to be the latest, but I would need that canonical logo and a new one... instagram... can you help?

**Comment by spencerbygraves** [comment]
@pmahnke sure, I'll update it.

**Comment by pmahnke** [comment]
@spencerbygraves it seems like there is a vanilla task to do this same work there... perhaps check with @kwm14 so you both don't do it?

**Comment by kwm14** [comment]
@spencerbygraves @pmahnke 

Yes it's currently in our backlog as a work [item](https://app.zenhub.com/workspace/o/ubuntudesign/vanilla-design/issues/92) as part of our blog components which were decided from our one-day workshop.

This piece of work hasn't been planned yet but if it's a blocker I can try to make it part of our next iteration?

**Comment by pmahnke** [comment]
@kwm14 that would be helpful if there is room!

**Comment by spencerbygraves** [comment]
ok, I'll leave it to @kwm14 then.

https://github.com/ubuntudesign/vanilla-design/issues/92
