### ISSUE TITLE
Finish cleanup of design.u.com (remove and update pages)

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/design.ubuntu.com#36]
See the [brief](https://docs.google.com/document/d/11y6o7Qq1c8aeiGEZJxXwKiKEE7QFQYJ_rNJ0_lX2umg/edit#) for details

**Comment by frankiegranato** [comment]
@deadlight I've moved this card to the Triaged pipeline because we decided this was out of scope for this current iteration.

**Comment by frankiegranato** [comment]
Tasks list:

NB: links to all copyodcs can be found here: https://drive.google.com/open?id=1f2YpIV4l0CTT7wQinY-KoU8XKswAaRoU7lffgdgugGw

- Home - Copy changes made, needs to be done on live
- Audiences - REMOVE PAGE
- Brand - Copy changes made and updated design done. Build not done. 
- Ubuntu logo - No changes
- Canonical logo - No changes
- Ubuntu partner logos - No changes
- Colour palette - Changes not made to copy doc yet. Issue to be assigned to Marcus. 
- Pictograms  - Changes made directly in WordPress
- Font (old page)  - REMOVE PAGE
- Charts and diagrams - Hide page until updated. Issue to be assigned to Marcus.
- Screenshots - Changes not made to copy doc yet. Issue to be assigned to Marcus.
- Product photography - Changes made directly in WordPress.
- Photography - Hide page until updated. Issue to be assigned to Marcus.
- Dot patterns - REMOVE PAGE
- Text  - REMOVE PAGE
Web - This page is to be updated and the current content replaced with copy doc. The url should be /web.
- Web Style Guide - To be hidden (in nav). Add a disclaimer to page (FG to add this to the copydoc. The vanilla "notification" pattern should be used)
- Font (new)  - Should appear in top level nav, new design, all content on copydoc should be included on the page.
- Apps  - REMOVE PAGE (Check with peter that a docs page has been made and that a redirect is appropriate)
- Scopes  - REMOVE PAGE (Check with peter that a docs page has been made and that a redirect is appropriate)
- Examples - REMOVE PAGE
- Downloads - Update filters as described in copy doc

**Comment by frankiegranato** [comment]
Remove the following pages:
/apps  (add redirect to https://docs.ubuntu.com/phone/en/apps/index) 
/scopes (add redirect to https://docs.ubuntu.com/phone/en/scopes/index)
/examples 
/audiences 
/text

Hide (in nav) the following pages:
/illustration 
/photography 
/web-style-guide (make update as described in copydoc)

**Comment by deadlight** [comment]
We've split this out into separate tasks
