### ISSUE TITLE
Update /web

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/design.ubuntu.com#43]
## Summary

Update /web page from the copydoc

**Comment by deadlight** [comment]
@frankiegranato : can you find the copydoc for this page, please?

**Comment by frankiegranato** [comment]
Karl, I'm not at my laptop and I'm not clear which copydoc you're after but
there's a very useful spreadsheet that Lil created for des.u.com with links
to all copydocs and issues. I link to it in the issue and on the brief.

**Comment by deadlight** [comment]
@frankiegranato no worries. I think I've found everything I need. Thanks
