### ISSUE TITLE
Use Vanilla back to top pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/design.ubuntu.com#88]
The back to top links are currently locally styled. Please convert to use: https://docs.vanillaframework.io/en/patterns/links#back-to-top-link.

**Comment by kwm14** [comment]
@anthonydillon I can't see a 'Back to top' link on any other the pages. Is this issue still valid? Alternatively we could add the link in as 'Downloads' is a pretty long page.

**Comment by anthonydillon** [comment]
This is no longer validate as the site has been completely rebuilt.
